// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmlib from "wasmlib";
import * as sc from "./index";

export const IdxParamAmount = 0;
export const IdxParamBuyer = 1;
export const IdxParamFarmer = 2;
export const IdxParamOwner = 3;
export const IdxParamRetailer = 4;
export const IdxResultOwner = 5;
export const IdxStateTransactions = 6;

export let keyMap: string[] = [
	sc.ParamAmount,
	sc.ParamBuyer,
	sc.ParamFarmer,
	sc.ParamOwner,
	sc.ParamRetailer,
	sc.ResultOwner,
	sc.StateTransactions,
];

export let idxMap: wasmlib.Key32[] = new Array(keyMap.length);
