// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmlib from "wasmlib";
import * as sc from "./index";

export class ArrayOfImmutableTransaction {
	objID: i32;

    constructor(objID: i32) {
        this.objID = objID;
    }

    length(): i32 {
        return wasmlib.getLength(this.objID);
    }

	getTransaction(index: i32): sc.ImmutableTransaction {
		return new sc.ImmutableTransaction(this.objID, new wasmlib.Key32(index));
	}
}

export class ImmutableFarmFairState extends wasmlib.ScMapID {

    transactions(): sc.ArrayOfImmutableTransaction {
		let arrID = wasmlib.getObjectID(this.mapID, sc.idxMap[sc.IdxStateTransactions], wasmlib.TYPE_ARRAY|wasmlib.TYPE_BYTES);
		return new sc.ArrayOfImmutableTransaction(arrID);
	}
}

export class ArrayOfMutableTransaction {
	objID: i32;

    constructor(objID: i32) {
        this.objID = objID;
    }

    clear(): void {
        wasmlib.clear(this.objID);
    }

    length(): i32 {
        return wasmlib.getLength(this.objID);
    }

	getTransaction(index: i32): sc.MutableTransaction {
		return new sc.MutableTransaction(this.objID, new wasmlib.Key32(index));
	}
}

export class MutableFarmFairState extends wasmlib.ScMapID {

    transactions(): sc.ArrayOfMutableTransaction {
		let arrID = wasmlib.getObjectID(this.mapID, sc.idxMap[sc.IdxStateTransactions], wasmlib.TYPE_ARRAY|wasmlib.TYPE_BYTES);
		return new sc.ArrayOfMutableTransaction(arrID);
	}
}
